language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs-v1.0"
  - "iojs-v2.0"
  - "iojs-v3.0"
  - "iojs"
env:
  - CXX=g++ CC=gcc
  - CXX=clang++ CC=clang NPMOPT=--clang=1
before_install:
  - sudo pip install cpp-coveralls coveralls-merge
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -y -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -y -qq g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; fi
install:
  - env LDFLAGS=--coverage CFLAGS="$CFLAGS --coverage" CXXFLAGS="$CXXFLAGS --coverage" npm install $NPMOPT
script:
  - ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec -s 200
after_success:
  - cpp-coveralls --gcov-options '\-lp' --build-root build --exclude build/liblzma --exclude node_modules --dump coverage/cppfiles.json
  - ./node_modules/coveralls/bin/coveralls.js --stdout < coverage/lcov.info > coverage/jsfiles.json
  - coveralls-merge coverage/jsfiles.json coverage/cppfiles.json
