language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs-v1.0"
sudo: false
cache:
  - pip
  - apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libstdc++-4.8-dev
env:
  - CXX=g++ CC=gcc
  - CXX=clang++ CC=clang NPMOPT=--clang=1
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user cpp-coveralls coveralls-merge
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
install:
  - env LDFLAGS=--coverage CFLAGS="$CFLAGS --coverage" CXXFLAGS="$CXXFLAGS --coverage" npm install $NPMOPT
script:
  - ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec -s 200
after_success:
  - cpp-coveralls --gcov-options '\-lp' --build-root build --exclude build/liblzma --exclude node_modules --dump coverage/cppfiles.json
  - ./node_modules/coveralls/bin/coveralls.js --stdout < coverage/lcov.info > coverage/jsfiles.json
  - coveralls-merge coverage/jsfiles.json coverage/cppfiles.json
