language: c++
compiler:
  - clang
  - gcc
env:
  - TRAVIS_NODE_VERSION=0.12
  - TRAVIS_NODE_VERSION=0.10
  - TRAVIS_NODE_VERSION=iojs-v1.0
  - TRAVIS_NODE_VERSION=iojs-v2.0
  - TRAVIS_NODE_VERSION=iojs-v3.0
  - TRAVIS_NODE_VERSION=4.0.0
os:
  - linux
  - osx
sudo: false
cache:
  - pip
  - apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libstdc++-4.8-dev
before_install:
  - echo "$TRAVIS_NODE_VERSION"
  - export PATH=$HOME/.local/bin:$PATH
  # dummy 7z because npm wants to run the prepublish script
  - mkdir -p $HOME/.local/bin/ && touch $HOME/.local/bin/7z && chmod +x $HOME/.local/bin/7z 
  # coveralls
  - pip install --user cpp-coveralls coveralls-merge
  # compilers
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ]; then export NPMOPT=--clang=1; fi
  # node versions
  - rm -rf ~/.nvm
  - git clone --branch v0.23.3 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install "$TRAVIS_NODE_VERSION"
  - node --version
install:
  - env LDFLAGS=--coverage CFLAGS="$CFLAGS --coverage" CXXFLAGS="$CXXFLAGS --coverage" npm install $NPMOPT
script:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec -s 1000 -t 5000
after_success:
  - cpp-coveralls --gcov-options '\-lp' --build-root build --exclude build/liblzma --exclude node_modules --dump coverage/cppfiles.json
  - ./node_modules/coveralls/bin/coveralls.js --stdout < coverage/lcov.info > coverage/jsfiles.json
  - coveralls-merge coverage/jsfiles.json coverage/cppfiles.json
