environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1.0"
    - nodejs_version: "2.0"
    - nodejs_version: "2.5"
    - nodejs_version: "3.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm run prepublish
  - npm install

test_script:
  - npm test
